### ISSUE TITLE
Microsoft SP Drive Request: Cannot parse the body of the sharepoint drive request. requestFolderItems

### ISSUE THREAD

**Issue by karunkshrestha** [gwsn/sharepoint-sdk#1] opened 2022-06-23 12:50 UTC
Hello,

I am getting the following error message when i try to connect to sharepoint.

Microsoft SP Drive Request: Cannot parse the body of the sharepoint drive request. requestFolderItems

I turned on the debug mode for the guzzle http client and the last successful call is to shown below.

I have replaced the ids with the named of the field e.g. {documentLibraryItemId}

GET https://graph.microsoft.com/v1.0/drives/{documentLibraryItemId}/items/root:/:/children

Response:
```{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#drives('{documentLibraryItem}')/items/$entity",
    "createdDateTime": "2021-04-11T00:40:33Z",
    "id": "{itemId}",
    "lastModifiedDateTime": "2022-06-23T11:08:35Z",
    "name": "root",
    "webUrl": "https://{tenant}.sharepoint.com/sites/{slug-name}/Shared%20Documents",
    "size": 48162077663,
    "parentReference": {
        "driveType": "documentLibrary",
        "driveId": "{parentDocumentLibraryId}"
    },
    "fileSystemInfo": {
        "createdDateTime": "2021-04-11T00:40:33Z",
        "lastModifiedDateTime": "2022-06-23T11:08:35Z"
    },
    "folder": {
        "childCount": 27
    },
    "root": {}
}
```

Then the following exception is thrown.

```  Exception 

  Microsoft SP Drive Request: Cannot parse the body of the sharepoint drive request. requestFolderItems

  at vendor/gwsn/sharepoint-sdk/src/Drive/FolderService.php:115
    111▕         // /sites/{siteId}/drive
    112▕         $response = $this->apiConnector->request('GET', $url);
    113▕ 
    114▕         if ( ! isset($response['value'])) {
  ➜ 115▕             throw new \Exception('Microsoft SP Drive Request: Cannot parse the body of the sharepoint drive request. ' . __FUNCTION__, 2321);
    116▕         }
    117▕ 
    118▕         return $response['value'];
    119▕     }

      +3 vendor frames 
  4   routes/console.php:22
      Illuminate\Filesystem\FilesystemAdapter::files()

      +13 vendor frames 
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Is there something missing in the config?

Setup
Laravel 9
"gwsn/flysystem-sharepoint-adapter": "^1.0",

filesystem.php
```
        'sharepoint' => [
            'driver' => 'sharepoint',
            'tenant_id' => '{tenantId}',
            'client_id' => '{clientId}',
            'client_secret' => '{clientSecret}',
            'sharepoint_site' => '{slugName}',
        ]
```
Thanks

**Comment by jnovermars** [comment] 2022-06-23 20:43
Thanks for taking the effort to make an issue on Github, i see that the actual error is coming from [Sharepoint SDK](https://github.com/gwsn/sharepoint-sdk) and not the Flysystem wrapper. 

This is not a big deal because it is also one of our packages and also a dependency of this package and it should work as intended. 

First, we need to try to reproduce the error before we can understand the issue, so I will try to set up a clean Laravel 9 project (we tested it with Symfony but this should not make a difference) and check if we can reproduce the error.

Besides that just to be sure can you confirm that you did perform the steps to prepare the Sharepoint so that it is accessible by the API (client_id and client_secret)?

**Comment by karunkshrestha** [comment] 2022-06-24 08:27
Thanks for looking into it @xleeuwx 

I have followed your very helpful readme guide to setup the app registration and clients. The Sharepoint API is accessible with these config as I can trace the API calls by enabling the debug mode on vendor/gwsn/sharepoint-sdk/src/ApiConnector.php line 97
```   try {
            $this->client = new Client([
                'base_uri' => $this->getBaseUrl(),
                'allow_redirects' => [
                    'max'             => 10,        // allow at most 10 redirects.
                    'strict'          => true,      // use "strict" RFC compliant redirects.
                    'referer'         => true,      // add a Referer header
                    'protocols'       => ['https'], // only allow https URLs
                    'track_redirects' => true
                ],
                'http_errors' => false,
                'timeout' => $this->getRequestTimeout(),
                'debug' => true
            ]);
        } catch (Exception $exception) {
            throw new Exception('Failed to setup web client, make sure the tenant and site are correct and you are connected to the internet!', 500, $exception);
        }
```
System config
PHP 8.1.7
Laravel 9

Please see attached composer.json and composer.lock files if you want to run it locally.
[composer-gwsn.zip](https://github.com/gwsn/sharepoint-sdk/files/8974498/composer-gwsn.zip)

**Comment by karunkshrestha** [comment] 2022-06-24 08:33
Also, two additional changes required to register the adapter.

_**app/Providers/AppServiceProvider.php**_
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Storage;
use League\Flysystem\Filesystem;
use GWSN\FlysystemSharepoint\FlysystemSharepointAdapter;
use GWSN\FlysystemSharepoint\SharepointConnector;
use Illuminate\Filesystem\FilesystemAdapter;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Storage::extend('sharepoint', function ($app, $config) {
            $adapter = new FlysystemSharepointAdapter(new SharepointConnector(
                $config['tenant_id'],
                $config['client_id'],
                $config['client_secret'],
                $config['sharepoint_site'],
            ));
 
            return new FilesystemAdapter(
                new Filesystem($adapter, $config),
                $adapter,
                $config
            );
        });
    }
}
```

_**config/filesystems.php**_

```
//Add to the list of disks.

        'sharepoint' => [
            'driver' => 'sharepoint',
            'tenant_id' => env('SHAREPOINT_TENANT_ID'),
            'client_id' => env('SHAREPOINT_CLIENT_ID'),
            'client_secret' => env('SHAREPOINT_CLIENT_SECRET'),
            'sharepoint_site' => env('SHAREPOINT_SITE_SLUG'),
        ]
```

**Comment by jnovermars** [comment] 2022-07-12 21:25
So i was able to reproduce the error, but it could be that we have the same error message with different problems. i was able to reproduce the error message when i was trying to get a directories from a directory that not exists.

I updated the README of the Flysystem adapter on how i used the Laravel driver (similar on what you did):
https://github.com/gwsn/flysystem-sharepoint-adapter/blob/main/README.md

Example:
```PHP
class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function index() {

        try {
            echo '<pre>';
            // Default writing of a file to SP
            Storage::disk('sharepoint')->put('test.txt', 'testContent');
            var_dump( Storage::disk('sharepoint')->get('test.txt'));
            echo '<br />';
            // Read the directory dummy where there is 1 file and 1 folder in this directory
            var_dump(Storage::disk('sharepoint')->directories('dummy', true));
            var_dump(Storage::disk('sharepoint')->files('dummy', true));
            echo '<br />';
            // Read a directory where the directory does not exists
            var_dump(Storage::disk('sharepoint')->directories('notExists', true));
            var_dump(Storage::disk('sharepoint')->files('notExists', true));
        } catch (\Exception $exception) {
            dd($exception);
        }


        return 'error';
    }
}
```

my output of this controller is:
```
String(11) "testContent"

array(1) {
  [0]=>
  string(10) "testFolder"
}
array(1) {
  [0]=>
  string(8) "test.txt"
}

^ Exception {#288 ▼
  #message: "Microsoft SP Drive Request: Cannot get folder items for folder that not exists, please create the folder first!. requestFolderItems"
  #code: 2321
  #file: "/Users/mySecretUser/laravelTest/vendor/gwsn/sharepoint-sdk/src/Drive/FolderService.php"
  #line: 114
  trace: {▶}
}
```

Could you update the both repositories to the latest versions and see if this fixed your issue?
https://github.com/gwsn/flysystem-sharepoint-adapter -> 1.0.4
https://github.com/gwsn/sharepoint-sdk -> 1.0.5


If this did not fixed your issue could you provide me the exact Flysystem function you try to use and check if the directory (including the prefix in the config) actually exists so i can try to reproduce your issue.

**Comment by jnovermars** [comment] 2022-08-15 11:14
@karunkshrestha do you have any update on this? Otherwise i will close the issue as fixed

**Comment by jnovermars** [comment] 2022-08-18 13:50
as there is no information anymore we cannot find out if the issue is fixed correctly so we are closing the issue until there is new information that it is not fixed.

**Closed as completed by jnovermars** 2022-08-18 13:50 UTC
Labels: bug, help wanted, question
